doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: true
            filix_company:
                url: '%env(resolve:DATABASE_URL_FILIX)%'
                profiling_collect_backtrace: true
            acme_company:
                url: '%env(resolve:DATABASE_URL_ACME)%'
                profiling_collect_backtrace: true
            umbrella_company:
                url: '%env(resolve:DATABASE_URL_UMBRELLA)%'
                profiling_collect_backtrace: true

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        entity_managers:
            default:
                connection: default
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: false
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App'
                        alias: App
            filix_company:
                connection: filix_company
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: false
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App'
                        alias: App
            acme_company:
                connection: acme_company
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: false
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App'
                        alias: App
            umbrella_company:
                connection: umbrella_company
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: false
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App'
                        alias: App
        #        auto_generate_proxy_classes: true
        #        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #        auto_mapping: true
        #        mappings:
        #            App:
        #                is_bundle: false
        #                type: yml
        #                dir: '%kernel.project_dir%/config/doctrine'
        #                prefix: 'App'
        #                alias: App

imports:
    resource: '../doctrine/types/*.yaml'