exercise_html_purifier:
    default_cache_serializer_path: '%kernel.cache_dir%/../htmlpurifier'

    html_profiles:
        default:
            config:
                # the charset used by the original contents
                Core.Encoding: 'UTF-8'
                # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html
                HTML.Allowed:
                    div[style],
                    a[href|target],
                    ul,ol,li,
                    br,b,i,u,strike,p[style],span[style],font[size]

# Read the https://github.com/Exercise/HTMLPurifierBundle/blob/master/README.md file
# to know how to whitelist elements

#            # whitelist attributes by tag
#            attributes:
#                div:
#                    class

#            # whitelist elements by name
#            elements:
#                b:
#                    - Block
#                    - Flow
#                    - Common

#            # list of elements that cannot have attributes
#            blank_elements: []
