App\Customization\Domain\CookiesPolicy:
  type: entity
  table: cookies_policy
#todo store Policies in one table
#  table: policy
  id:
    id:
      type: uuid
      unique: true
#      generator:
#        strategy: CUSTOM
#      customIdGenerator:
#        class: Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator
  fields:
#    content:
#      type:
#        json
    title:
      type:
        string
    description:
      type:
        text
  manyToOne:
    language:
      targetEntity: App\Shared\Domain\Language