App\Customization\Domain\Question:
  type: entity
  table: question
#  gedmo:
#    soft_deleteable:
#      field_name: deleted
#      time_aware: true
  id:
    id:
      type: uuid
      unique: true
#      generator:
#        strategy: CUSTOM
#      customIdGenerator:
#        class: Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator
  fields:
    orderIndex:
      type:
        smallint
      unique: true
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    deleted:
      type: datetime
      nullable: true
  oneToMany:
    translations:
      targetEntity: App\Customization\Domain\QuestionTranslation
      mappedBy: question
      cascade: [ "all" ]
      onDelete: CASCADE