App\Identity\Domain\PasswordRecoveryToken\PasswordRecoveryToken:
  type: entity
  table: user_password_recovery
  id:
    user_id:
      type: user_id
  fields:
    token:
      type: string
      length: 180