# TODO use inheritanceType: SINGLE_TABLE for single table sharing with Customer entity
App\Identity\Domain\Customer\BannedCustomer:
  type: entity
#  inheritanceType: SINGLE_TABLE
#  discriminatorColumn:
#    name: discr
#    type: string
#  discriminatorMap:
#    Customer: App\Identity\Domain\Customer\Customer
#    NotActivatedCustomer: App\Identity\Domain\Customer\NotActivatedCustomer
#    DeletedCustomer: App\Identity\Domain\Customer\DeletedCustomer
#  table: customer
#  repositoryClass: App\Identity\Infrastructure\Customer\Persistence\Doctrine\NotActivatedCustomerIdentityByTenantRepository
#  id:
#    id:
#      type: customer_id
#      unique: true
#      generator:
#        strategy: CUSTOM
#      customIdGenerator:
#        class: Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator
#  fields:
#    email:
#      type: string
#    username:
#      type: string
#      nullable: true
#    password:
#      type: string
#      nullable: true
#    firstname:
#      type: string
#      nullable: true
#    lastname:
#      type: string
#      nullable: true
#    birthday:
#      type: datetime
#      nullable: true
#    gender:
#      type: string
#      nullable: true
#    postal:
#      type: string
#      nullable: true
#    photo:
#      type: string
#      nullable: true