App\Initiative\Domain\Questionnaire\Answer:
  type: entity
  table: questionnaire_answer
  id:
    id:
      type: uuid
      unique: true
  fields:
    freetext:
      type: text
  manyToOne:
    questionnaire:
      targetEntity: App\Initiative\Domain\Questionnaire\Questionnaire
      inversedBy: answers
    answerer:
      targetEntity: App\Identity\Domain\Customer\AbstractCustomer
#      inversedBy: questionnaireAnswers
    option:
      targetEntity: App\Initiative\Domain\Questionnaire\Option
#      inversedBy: answers
